<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <title>Icinga 2 Web Install Wizard</title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">

  <link rel="stylesheet" href="<?php echo $this->baseUrl('css/vendor/bootstrap/bootstrap.min.css') ?>" media="screen">

  <!--
  Not used until styling is clear (see #4550)
  <link rel="stylesheet" href="<?php echo $this->baseUrl('css.php') ?>">
  -->
</head>
<body>
<?php echo $this->render('body.phtml'); ?>

</body>
</html>